import {
  Home,
  Users,
  BookOpen,
  Briefcase,
  Calendar,
  DollarSign,
  CreditCard,
  Send,
  BarChart2,
  FileText,
  UserPlus,
  Bell,
  User,
  LogOut,
} from 'react-feather';

export const MENU_ITEMS = {
  admin: [
    { id: 'dashboard', label: 'Dashboard', icon: Home, component: 'AdminHome', path: '/dashboard/dashboard' },
    { id: 'students', label: 'Students', icon: Users, component: 'StudentsList', path: '/dashboard/students' },
    { id: 'teachers', label: 'Teachers', icon: Users, component: 'TeachersList', path: '/dashboard/teachers' },
    { id: 'admin', label: 'Admin', icon: Users, component: 'AdminList', path: '/dashboard/admin' },
    { id: 'staff', label: 'Staff', icon: Briefcase, component: 'StaffList', path: '/dashboard/staff' },
    { id: 'adduser', label: 'Add User', icon: UserPlus, component: 'AddUser', path: '/dashboard/adduser' },
    { id: 'classes', label: 'Classes', icon: BookOpen, component: 'ClassesList', path: '/dashboard/classes' },
    { id: 'subjects', label: 'Subjects', icon: BookOpen, component: 'SubjectsList', path: '/dashboard/subjects' },
    { id: 'fee-structure', label: 'Fee Structure', icon: DollarSign, component: 'FeeStructureList', path: '/dashboard/fee-structure' },
    { id: 'fee-payments', label: 'Fee Payments', icon: CreditCard, component: 'FeePaymentsManager', path: '/dashboard/fee-payments' },
    { id: 'salary-structure', label: 'Salary Structure', icon: CreditCard, component: 'SalaryStructureList', path: '/dashboard/salary-structure' },
    { id: 'salary-payments', label: 'Salary Payments', icon: CreditCard, component: 'SalaryPaymentsManager', path: '/dashboard/salary-payments' },
    { id: 'my-salary', label: 'My Salary', icon: DollarSign, component: 'MySalary', path: '/dashboard/my-salary' },
    { id: 'fee-matrix', label: 'Fee Matrix', icon: BarChart2, component: 'FeeMatrix', path: '/dashboard/fee-matrix' },
    { id: 'salary-matrix', label: 'Salary Matrix', icon: BarChart2, component: 'SalaryMatrix', path: '/dashboard/salary-matrix' },
    { id: 'create-alert', label: 'Create Alert', icon: Send, component: 'CreateAlert', path: '/dashboard/create-alert' },
    { id: 'my-alerts', label: 'My Alerts', icon: Bell, component: 'MyAlerts', path: '/dashboard/my-alerts' },
    { id: 'attendance', label: 'Attendance', icon: Calendar, component: 'AttendanceMarkForm', path: '/dashboard/attendance' },
    { id: 'notices', label: 'Notices', icon: Bell, component: 'NoticesList', path: '/dashboard/notices' },
    { id: 'profile', label: 'Profile', icon: User, component: 'ProfileView', path: '/dashboard/profile' },
    { id: 'logout', label: 'Logout', icon: LogOut, component: 'Logout' },
  ],
  teacher: [
    { id: 'dashboard', label: 'Dashboard', icon: Home, component: 'TeacherHome', path: '/dashboard/dashboard' },
    { id: 'students', label: 'Students', icon: Users, component: 'StudentsList', path: '/dashboard/students' },
    { id: 'subjects', label: 'My Subjects', icon: BookOpen, component: 'SubjectsList', path: '/dashboard/subjects' },
    { id: 'attendance', label: 'Attendance', icon: Calendar, component: 'AttendanceMarkForm', path: '/dashboard/attendance' },
    { id: 'my-salary', label: 'My Salary', icon: DollarSign, component: 'MySalary', path: '/dashboard/my-salary' },
    { id: 'my-alerts', label: 'My Alerts', icon: Bell, component: 'MyAlerts', path: '/dashboard/my-alerts' },
    { id: 'profile', label: 'Profile', icon: User, component: 'ProfileView', path: '/dashboard/profile' },
    { id: 'logout', label: 'Logout', icon: LogOut, component: 'Logout' },
  ],
  student: [
    { id: 'dashboard', label: 'Dashboard', icon: Home, component: 'StudentHome', path: '/dashboard/dashboard' },
    { id: 'attendance', label: 'Attendance', icon: Calendar, component: 'MyAttendance', path: '/dashboard/attendance' },
    { id: 'performance', label: 'Performance', icon: Calendar, component: 'PerformanceForm', path: '/dashboard/performance' },
    { id: 'my-alerts', label: 'My Alerts', icon: Bell, component: 'MyAlerts', path: '/dashboard/my-alerts' },
    { id: 'profile', label: 'Profile', icon: User, component: 'ProfileView', path: '/dashboard/profile' },
    { id: 'logout', label: 'Logout', icon: LogOut, component: 'Logout' },
  ],
  staff: [
    { id: 'dashboard', label: 'Dashboard', icon: Home, component: 'StaffHome', path: '/dashboard/dashboard' },
    { id: 'attendance', label: 'My Attendance', icon: Calendar, component: 'MyAttendance', path: '/dashboard/attendance' },
    { id: 'my-salary', label: 'My Salary', icon: DollarSign, component: 'MySalary', path: '/dashboard/my-salary' },
    { id: 'my-alerts', label: 'My Alerts', icon: Bell, component: 'MyAlerts', path: '/dashboard/my-alerts' },
    { id: 'profile', label: 'Profile', icon: User, component: 'ProfileView', path: '/dashboard/profile' },
    { id: 'logout', label: 'Logout', icon: LogOut, component: 'Logout' },
  ],
};

export default MENU_ITEMS;
